

class DataIngestionArtifact:
    pass


class DataValidationArtifact:...
class DataTransformationArtifact:...
class ModelTraninerArtifact:...
class ModelEvaluationArtifact:...
class ModelPusherArtifact:...
